### PR TITLE
Add Microsoft Teams - Quick Access

### PR DESCRIPTION
**Pull request by justin025**
Based on Microsoft To Do

https://file.io/dRcdmh7h98a6
I alternatively have a png logos here that match the style of your other app icons, but was unsure how to convert it to svg without losing quality.

### CODE REVIEW

**Comment by tdmrhn** [comment]
You can find it here;;
https://upload.wikimedia.org/wikipedia/commons/c/c9/Microsoft_Office_Teams_%282018%E2%80%93present%29.svg

**Comment by justin025** [comment]
I fetched the current icon from wikipedia, I meant that all of your apps are squared off and figured it would make more sense to match the style if you don't mind including a png.

current:

png:

**Comment by tdmrhn** [comment]
It is live :)
https://addons.thunderbird.net/en-GB/thunderbird/addon/microsoft-teams-quick-access/

**Comment by justin025** [comment]
Thank you

**Pull request merged**
