### PR TITLE
Add Trello support

### PR DESCRIPTION
**Pull request by fpusan**
Also tried to copy how you were doing things in order to create an access button for the Trello web interface.
It seems to work in my computer, hope it can help!

### CODE REVIEW

**Review by tdmrhn — CHANGES_REQUESTED** [review]
Can you change version to 0.1, also if it doesn't have a browser check then the browser manipulation is not necessary.

**Comment by tdmrhn** [comment]
You can check/change/test Discord as an example.

**Comment by fpusan** [comment]
Changed version to 0.1.
Kept the browser manipulation since removing it lead to a pop-up in my Trello window saying "This browser is not supported. You may need to upgrade to the latest version" (although things worked well otherwise)

**Comment by tdmrhn** [comment]
Thnaks for the PR, it is live;
https://addons.thunderbird.net/en-GB/thunderbird/addon/trello-quick-access/

**Pull request merged**
